site_name: Online Judge Docs
theme: yeti
docs_dir: 'src'
site_dir: 'docs'
pages:
 - Home: 'index.md'
 - Judger: 
#    - 'Index': 'judger/index.md'
    - 'English': 
        - 'API': 'judger/English/index.md'
 - JudgeServer:
#    - 'Index': 'judge_server/index.md'
    - 'English':
        - 'API': 'judge_server/English/index.md'
        - 'Deploy': 'judge_server/English/deploy.md'
#    - '中文':
#        - 'API': 'judge_server/Chinese/index.md'
#        - '部署': 'judge_server/Chinese/deploy.md'

